name: "Setup RISC-V toolchain (Ubuntu)"
description: "Installs RISC-V toolchain + exports bundled compat headers."
inputs:
  apt-cache:
    description: "Cache APT downloads"
    required: false
    default: 'true'
  cache-key-suffix:
    description: "Bump to bust APT cache"
    required: false
    default: 'v1'

runs:
  using: "composite"
  steps:
    # Ensure cache dirs exist even on first run
    - name: Prep APT cache dirs
      shell: bash
      run: |
        set -euxo pipefail
        mkdir -p "$HOME/.apt-cache/archives" "$HOME/.apt-cache/lists"

    # Restore cached APT bits
    - name: Restore APT cache
      if: inputs.apt-cache == 'true'
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.apt-cache/archives
          ~/.apt-cache/lists
        key: ${{ runner.os }}-apt-riscv-${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-apt-riscv-

    # Avoid slow man-db updates & shrink docs
    - name: Speed up apt
      shell: bash
      run: |
        set -euxo pipefail
        echo 'set man-db/auto-update false' | sudo debconf-communicate
        sudo rm -f /var/lib/man-db/auto-update || true
        echo 'path-exclude=/usr/share/man/*'   | sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc >/dev/null
        echo 'path-exclude=/usr/share/groff/*' | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc >/dev/null
        echo 'path-exclude=/usr/share/info/*'  | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc >/dev/null

    - name: Install toolchain and QEMU
      shell: bash
      run: |
        set -euxo pipefail
        sudo apt-get -o Dir::Cache::archives="$HOME/.apt-cache/archives" \
                     -o Dir::State::lists="$HOME/.apt-cache/lists" update
        sudo apt-get -o Dir::Cache::archives="$HOME/.apt-cache/archives" \
                     -o Dir::State::lists="$HOME/.apt-cache/lists" \
                     install -y --no-install-recommends \
                     build-essential make python3 ca-certificates \
                     gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf \
                     qemu-system-misc

    # Save cache early so later job failures don't prevent seeding
    - name: Save APT cache
      if: inputs.apt-cache == 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.apt-cache/archives
          ~/.apt-cache/lists
        key: ${{ runner.os }}-apt-riscv-${{ inputs.cache-key-suffix }}

    # Export bundled headers (repo root has /include)
    - name: Export CPATH/C_INCLUDE_PATH to bundled headers
      shell: bash
      run: |
        set -euxo pipefail
        ROOT="$(cd "${GITHUB_ACTION_PATH}/../.." && pwd)"
        HDRS="${ROOT}/include"
        # add compat/include if it exists
        [ -d "${ROOT}/compat/include" ] && HDRS="${HDRS}:${ROOT}/compat/include"
        echo "CPATH=${HDRS}${CPATH:+:$CPATH}" >> "$GITHUB_ENV"
        echo "C_INCLUDE_PATH=${HDRS}${C_INCLUDE_PATH:+:$C_INCLUDE_PATH}" >> "$GITHUB_ENV"
    
    - name: Disable bundled headers for the rest of the job
      run: |
        echo "CPATH=" >> "$GITHUB_ENV"
        echo "C_INCLUDE_PATH=" >> "$GITHUB_ENV"